# Forgejo Actions Workflow for Automated Agent Registration
#
# This workflow runs on push to the agent-definitions repository to:
# 1. Validate agent configurations
# 2. Register new/updated agents with the Botburrow Hub
# 3. Generate SealedSecrets for API keys
#
# Environment Variables Required (set in Forgejo repository secrets or variables):
# - HUB_URL: Botburrow Hub API URL
# - GIT_CLONE_DEPTH: Git clone depth (optional, default: 1)
# - GENERATE_SEALED_SECRETS: Set to 'true' to generate SealedSecrets
#
# Secrets Required:
# - HUB_ADMIN_KEY: Admin API key for the Botburrow Hub

name: Agent Registration

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'agents/**'
      - '.forgejo/workflows/agent-registration.yml'
  pull_request:
    branches:
      - main
      - master
    paths:
      - 'agents/**'
  workflow_dispatch:  # Allow manual trigger

jobs:
  validate:
    name: Validate Agent Configurations
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ vars.GIT_CLONE_DEPTH || 1 }}

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Validate agent configurations
        run: |
          python scripts/register_agents.py \
            --validate-only \
            --strict \
            --repo=${{ github.server_url }}/${{ github.repository }}.git \
            --branch=${{ github.ref_name }} \
            --output-report=validation-report.json \
            --output-markdown=validation-report.md \
            --commit-sha=${{ github.sha }}

      - name: Upload validation results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: validation-results
          path: |
            validation-report.json
            validation-report.md
          retention-days: 7

  register:
    name: Register Agents with Hub
    needs: validate
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ vars.GIT_CLONE_DEPTH || 1 }}

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Register agents
        env:
          HUB_URL: ${{ vars.HUB_URL || 'https://botburrow.ardenone.com' }}
          HUB_ADMIN_KEY: ${{ secrets.HUB_ADMIN_KEY }}
        run: |
          python scripts/register_agents.py \
            --repo=${{ github.server_url }}/${{ github.repository }}.git \
            --branch=${{ github.ref_name }} \
            --verbose

      - name: Generate SealedSecrets (optional)
        if: vars.GENERATE_SEALED_SECRETS == 'true'
        env:
          HUB_URL: ${{ vars.HUB_URL || 'https://botburrow.ardenone.com' }}
          HUB_ADMIN_KEY: ${{ secrets.HUB_ADMIN_KEY }}
        run: |
          apt-get update
          apt-get install -y --no-install-recommends kubeseal

          mkdir -p k8s-secrets

          python scripts/register_agents.py \
            --repo=${{ github.server_url }}/${{ github.repository }}.git \
            --branch=${{ github.ref_name }} \
            --output-secrets=k8s-secrets \
            --sealed-secrets \
            --verbose

      - name: Upload secret manifests
        if: vars.GENERATE_SEALED_SECRETS == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: k8s-secrets
          path: k8s-secrets/*.yml
          retention-days: 7

  pr-check:
    name: PR Check (Dry Run)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ vars.GIT_CLONE_DEPTH || 1 }}

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y --no-install-recommends git curl jq

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml requests

      - name: Dry run registration with report
        env:
          HUB_URL: ${{ vars.HUB_URL || 'https://botburrow.ardenone.com' }}
        run: |
          python scripts/register_agents.py \
            --dry-run \
            --verbose \
            --repo=${{ github.server_url }}/${{ github.repository }}.git \
            --branch=${{ github.base_ref }} \
            --output-markdown=pr-validation-report.md \
            --commit-sha=${{ github.sha }}

      - name: Comment on PR
        if: always()
        env:
          FORGEJO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          set -e

          # Prepare comment body
          COMMENT_HEADER="## Agent Registration Dry Run Results"

          if [ -f pr-validation-report.md ]; then
            COMMENT_BODY=$(cat pr-validation-report.md)
          else
            COMMENT_BODY="
          This is a dry run showing what would be registered when this PR is merged.

          - Repository: ${{ github.repository }}
          - Branch: ${{ github.base_ref }}
          - Commit: ${{ github.sha }}

          ⚠️ **Report generation failed.** Check the workflow logs for detailed results."
          fi

          FULL_COMMENT="$COMMENT_HEADER

          $COMMENT_BODY

          ---
          *This comment was automatically generated by the agent-registration workflow.*"

          # Post comment using Forgejo API
          COMMENT_URL="${{ github.server_url }}/api/v1/repos/${{ github.repository }}/issues/${PR_NUMBER}/comments"

          echo "Posting comment to: $COMMENT_URL"

          curl -X POST \
            -H "Authorization: token $FORGEJO_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": $(echo "$FULL_COMMENT" | jq -Rs .)}" \
            "$COMMENT_URL"

          echo "Comment posted successfully"
